name: GitHub Actions Demo
run-name: ${{ github.actor }} estÃ¡ probando GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ El trabajo fue activado automÃ¡ticamente por un evento ${{ github.event_name }}."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” Â¡Este trabajo ahora se estÃ¡ ejecutando en un servidor ${{ runner.os }} alojado en GitHub!"
      - name: Consultar el cÃ³digo del repositorio
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ El repositorio ${{ github.repository }} se ha clonado en el ejecutor."
      - run: echo "ğŸ–¥ï¸ El flujo de trabajo ahora estÃ¡ listo para probar su cÃ³digo en el ejecutor."
      - name: Listar archivos en el repositorio
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ El estado de este trabajo es ${{ job.status }}."
